### ISSUE TITLE
I can´t start the bot 

### ISSUE THREAD

**Issue by peter9811** [ItamarRocha/binary-bot#2]
I dont understand a lot... this its all my "log", running the py through CMD

```
2020-05-18 17:47:18.414601: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-05-18 17:47:18.423083: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-05-18 17:47:23.581259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-05-18 17:47:24.232897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:04:00.0 name: GeForce 920M computeCapability: 3.5
coreClock: 0.954GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 13.41GiB/s
2020-05-18 17:47:24.256591: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-05-18 17:47:24.275917: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-05-18 17:47:24.296574: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-05-18 17:47:24.315652: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-05-18 17:47:24.336830: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-05-18 17:47:24.356607: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-05-18 17:47:24.378233: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-05-18 17:47:24.389219: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "D:\Downloads\binary-bot\testing.py", line 125, in <module>
    NAME = train_data() + '.model'
  File "D:\Downloads\binary-bot\training.py", line 89, in train_data
    iq = login()
  File "D:\Downloads\binary-bot\iq.py", line 20, in login
    iq.change_balance("PRACTICE") #or real
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\iqoptionapi\stable_api.py", line 430, in change_balance
    for balance in self.get_profile_ansyc()["balances"]:
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\iqoptionapi\stable_api.py", line 331, in get_profile_ansyc
    while self.api.profile.msg==None:
AttributeError: 'IQ_Option' object has no attribute 'api'
```

**Comment by peter9811** [comment]
I'm now installing NVIDIA CUDA, but I think what this isn't my problem...

**Comment by ItamarRocha** [comment]
Hi peter, I've never encountered this error. It seems to be something with the api. Try to check their issues on github to see if someone had a similar situation or ask it there. I'll try to see if I can solve the problem too. Any issues with the code just let me know.

**Comment by peter9811** [comment]
Can you help me how to force reinstall the API?

**Comment by ItamarRocha** [comment]
Hi peter, Read the log in there. It seems it didn't found your GPU. Try following the guide by tensorflow.
```shell
2020-05-18 17:47:24.389219: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```
