### ISSUE TITLE
Error loading DLL

### ISSUE THREAD

**Issue by garridez** [ItamarRocha/binary-bot#30]
python : Traceback (most recent call last):
No linha:1 caractere:1
+ python testing.py
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "testing.py", line 3, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 80, in <module>
    from .base import clone
  File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 62, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Não foi possível encontrar o módulo especificado

Could somebody help me?
Thank you!

**Comment by eortigoza5** [comment]
> python : Traceback (most recent call last): No linha:1 caractere:1
> 
> * python testing.py
> * ```
>     + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>   
>   File "testing.py", line 3, in <module>
>     from sklearn.preprocessing import MinMaxScaler
>   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 80, in <module>
>     from .base import clone
>   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 21, in <module>
>     from .utils import _IS_32BIT
>   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\__init__.py", line 20, in <module>
>     from scipy.sparse import issparse
>   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
>     from . import _distributor_init
>   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 62, in <module>
>     WinDLL(os.path.abspath(filename))
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
>   ```
> 
> OSError: [WinError 126] Não foi possível encontrar o módulo especificado
> 
> Could somebody help me? Thank you!

hi, just install [requirements.txt](https://github.com/ItamarRocha/binary-bot/blob/master/requirements.txt)
with command    pip install -r requirements.txt
it is in the main folder

**Comment by ericleonardo** [comment]
> > python : Traceback (most recent call last): No linha:1 caractere:1
> > 
> > * python testing.py
> > * ```
> >     + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
> >     + FullyQualifiedErrorId : NativeCommandError
> >   
> >   File "testing.py", line 3, in <module>
> >     from sklearn.preprocessing import MinMaxScaler
> >   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 80, in <module>
> >     from .base import clone
> >   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 21, in <module>
> >     from .utils import _IS_32BIT
> >   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\__init__.py", line 20, in <module>
> >     from scipy.sparse import issparse
> >   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
> >     from . import _distributor_init
> >   File "C:\Users\Diego\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 62, in <module>
> >     WinDLL(os.path.abspath(filename))
> >   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
> >     self._handle = _dlopen(self._name, mode)
> >   ```
> > 
> > OSError: [WinError 126] Não foi possível encontrar o módulo especificado
> > Could somebody help me? Thank you!
> 
> hi, just install [requirements.txt](https://github.com/ItamarRocha/binary-bot/blob/master/requirements.txt) with command pip install -r requirements.txt it is in the main folder

Hi, @eortigoza5 Please, are you using this IQ Option bot successfully?
What accuracy (win ratio) are you getting?
Thanks!
