### ISSUE TITLE
Problema ao Rodar o Sistema

### ISSUE THREAD

**Issue by dexter00x** [ItamarRocha/binary-bot#7]
Boa tarde!
Estou com um problema ao inicializar o testing.py.

C:\Users\Lemos\Downloads\binary-bot-master\binary-bot-master>python testing.py
2020-07-05 17:08:35.933108: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-05 17:08:35.944190: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-07-05 17:08:39.272856: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-05 17:08:39.280050: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-05 17:08:39.295328: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: BD-LEMOS
2020-07-05 17:08:39.303199: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: BD-LEMOS
Traceback (most recent call last):
  File "testing.py", line 125, in <module>
    NAME = train_data() + '.model'
  File "C:\Users\Lemos\Downloads\binary-bot-master\binary-bot-master\training.py", line 89, in train_data
    iq = login()
  File "C:\Users\Lemos\Downloads\binary-bot-master\binary-bot-master\iq.py", line 20, in login
    iq.change_balance("PRACTICE") #or real
  File "C:\Users\Lemos\AppData\Local\Programs\Python\Python37\lib\site-packages\iqoptionapi\stable_api.py", line 432, in change_balance
    for balance in self.get_profile_ansyc()["balances"]:
  File "C:\Users\Lemos\AppData\Local\Programs\Python\Python37\lib\site-packages\iqoptionapi\stable_api.py", line 339, in get_profile_ansyc
    while self.api.profile.msg == None:
AttributeError: 'IQ_Option' object has no attribute 'api'

Poderia me ajudar?

**Comment by ItamarRocha** [comment]
Eles lançaram uma nova versão da API. Meu repositório está desatualizado. Em breve vou corrigir e adaptar a nova.
